Experiment presentation
thesis20/report pull request #11
Opened 2020-11-25 09:00 UTC by Eduardsen

2020-11-25 09:22 UTC, andpaacoke commented on sections/investigations/protocol.tex
> +In terms of contextual information, the dataset provides \textit{year of birth} for the user, \textit{gender} and \textit{ager group} which is discretized as either child or adult.
```suggestion
In terms of contextual information, the dataset provides \textit{year of birth} for the user, \textit{gender} and \textit{age group} which is discretized as either child, adult or elder.
```

2020-11-25 09:22 UTC, andpaacoke commented on sections/investigations/protocol.tex
> +The movies are also linked to $32$ types of content information, such as \textit{synopsis}, \textit{running time}, \textit{release date}, \textit{list of genres} and \textit{list of crew members}.
Tror ikke vi har beskrevet knowledge graphs men hvis vi har kunne man skrive at denne information kunne bruges til at lave en knowledge graph

2020-11-25 09:22 UTC, andpaacoke commented on sections/investigations/protocol.tex
> +The same splits are used for evaluation for each method.
Det er nok åbenlyst men måske nævne hvorfor vi bruger samme splits

2020-11-25 09:22 UTC, andpaacoke commented on sections/investigations/protocol.tex
> +    \item \textbf{ItemAVG}: A global average of items as predictions
Tror faktisk det er wrong at skrive global average, da det nok betyder samlede average over alle items. Metoden er i stedet average rating for hvert item

2020-11-25 09:22 UTC, andpaacoke commented on sections/investigations/protocol.tex
> +    \item \textbf{TopPopular}
Mangler der en beskrivelse

2020-11-26 13:12 UTC, Moesgaarda requested changes

2020-11-26 13:12 UTC, Moesgaarda commented on sections/investigations/protocol.tex
> +The movies are also linked to $32$ types of content information, such as \textit{synopsis}, \textit{running time}, \textit{release date}, \textit{list of genres} and \textit{list of crew members}.
```suggestion
The movies are also linked to $32$ types of content information, such as \textit{synopsis}, \textit{running time}, \textit{release date}, \textit{list of genres} and \textit{list of crew members}.
This information can be used for methods that utilize knowledge, such as knowledge-graph-based methods.
```

2020-11-26 13:12 UTC, Moesgaarda commented on sections/investigations/protocol.tex
> +The same splits are used for evaluation for each method.
```suggestion
The same splits are used for evaluation for each method to ensure proper comparability between the methods.
```

2020-11-26 13:12 UTC, Moesgaarda commented on sections/investigations/protocol.tex
> +    \item \textbf{ItemAVG}: A global average of items as predictions
```suggestion
    \item \textbf{ItemAVG}: An average rating of the item across all users is used for predictions
```

2020-11-26 13:12 UTC, Moesgaarda commented on sections/investigations/protocol.tex
> +    \item \textbf{TopPopular}
```suggestion
    \item \textbf{TopPopular}: Always recommends the top k most popular items to a user
```

2020-11-26 13:12 UTC, Moesgaarda commented on sections/investigations/protocol.tex
> +    \item \textbf{ItemSplitting\cite{GraphBasedCollaborativePaper}}: A context based recommendation approach making use of transitivity in a bipartite graph to model and nearest neighbor similarity t
```suggestion
    \item \textbf{ItemSplitting\cite{GraphBasedCollaborativePaper}}: A context-based recommendation approach making use of transitive associations in a bipartite graph to model and find nearest neighbor similarity to produce recommendations on a dataset that has been split on items.
```

2020-11-26 13:58 UTC, Eduardsen commented on sections/investigations/protocol.tex
> +The movies are also linked to $32$ types of content information, such as \textit{synopsis}, \textit{running time}, \textit{release date}, \textit{list of genres} and \textit{list of crew members}.
trie

2020-11-26 14:03 UTC, Moesgaarda approved these changes

2020-11-26 15:00 UTC, andpaacoke approved these changes

2020-11-27 11:31 UTC, merged