Result extension
thesis20/report pull request #3
Opened 2020-10-28 08:44 UTC by Eduardsen

2020-11-02 08:08 UTC, Moesgaarda requested changes

2020-11-02 08:08 UTC, Moesgaarda commented on sections/Investigation/results.tex
> +Frappé collected implicit data on the following relevant context dimensions: time of day, weekday, whether or not it is weekend, at home or at work, weather, country, cost and city.
Vi har skrevet dimensions med italics i resten, enten skal det gøres her eller fjernes ved de andre

2020-11-02 08:08 UTC, Moesgaarda commented on sections/Investigation/results.tex
> +When evaluating recommender systems the relevant properties must be determined.
properties of what

2020-11-02 08:08 UTC, Moesgaarda commented on sections/Investigation/results.tex
> +\cite{RecommenderHandbook2015} defines a set of properties for recommender systems: \textit{user preference, prediction accuracy, coverage, confidence, trust, novelty, serendipity, diversity, utility
```suggestion
Ricci et al.\cite{RecommenderHandbook2015} defines a set of properties for recommender systems: \textit{user preference, prediction accuracy, coverage, confidence, trust, novelty, serendipity, diversity, utility, risk, robustness, privacy, adaptivity} and \textit{scalability}.
```

2020-11-02 08:08 UTC, Moesgaarda commented on sections/Investigation/results.tex
> +The f1-measure also employed by some of the papers summarizes precision and recall into a single number, defined by \autoref{eqn:f1}.
```suggestion
The F1-measure also employed by some of the papers summarizes precision and recall into a single number, defined by \autoref{eqn:f1}.
```

2020-11-02 08:08 UTC, Moesgaarda commented on sections/Investigation/results.tex
> +Finally, some of the papers use the Discounted Cumulative Gain(DCG) metric, or the normalized version NDCG.
```suggestion
Finally, some of the papers use the Discounted Cumulative Gain(DCG) metric or the normalized version NDCG.
```

2020-11-03 08:31 UTC, andpaacoke approved these changes

2020-11-03 08:36 UTC, Moesgaarda approved these changes

2020-11-03 09:12 UTC, merged