Evaluation examples
thesis20/report pull request #38
Opened 2020-12-14 11:56 UTC by andpaacoke

2020-12-14 21:40 UTC, Eduardsen commented on sections/experiments/datasets.tex
> +To give an example of the calculation of Precision(L), Recall(L) and F1-measure, a top $k$ set and a relevant item set is defined to be used for the calculation
```suggestion
To give an example of the calculation of Precision(L), Recall(L) and F1-measure, a top $k$ set and a relevant item set is defined to be used for the calculation.
```

2020-12-14 21:40 UTC, Eduardsen commented on sections/experiments/datasets.tex
> +To give an example of the calculation of Precision(L), Recall(L) and F1-measure, a top $k$ set and a relevant item set is defined to be used for the calculation
smid lige en ref en til din equation

2020-12-14 21:40 UTC, Eduardsen commented on sections/experiments/datasets.tex
> +The intersection between the top-k set, L(u), and the relevant items, T(u), is a set containing three items $\{item1, item3, item4\}$.
```suggestion
The intersection between the top $k$ set $L(u)$, and the relevant items $T(u)$, is a set containing three items $\{item1, item3, item4\}$.
```

2020-12-14 21:40 UTC, Eduardsen commented on sections/experiments/datasets.tex
> +    \text{Relevant-items} = \{item1, item3, item4, item5,\nonumber \\
tænker sættene her i equation nok skal hedde L(U) og T(u) når vi bruger det nedenunder til at beskrive dem

2020-12-14 21:40 UTC, Eduardsen commented on sections/experiments/datasets.tex
> +The lengths of the L(u) and T(u) sets in this example are both four and five respectively.
```suggestion
The lengths of the $L(u)$ and $T(u)$ sets in this example are four and five respectively.
```

2020-12-14 21:40 UTC, Eduardsen commented on sections/experiments/datasets.tex
> +These values are then plotted into the equations to get the precion and recall values.
```suggestion
These values are then plotted into the equations to get the precision and recall values.
```

2020-12-14 21:40 UTC, Eduardsen commented on sections/experiments/datasets.tex
> +    \text{Top-items} = \{item1, item2, item3, item4\}\label{eqn:item-lists}
```suggestion
    \text{Top-items} = \{item1, \: item2, \: item3, \: item4\}\label{eqn:item-lists}
```

2020-12-14 21:40 UTC, Eduardsen commented on sections/experiments/datasets.tex
> +    \text{Relevant-items} = \{item1, item3, item4, item5,\nonumber \\
```suggestion
    \text{Relevant-items} = \{item1, \: item3, \: item4, \: item5,\nonumber \\
```

2020-12-14 21:40 UTC, Eduardsen commented on sections/experiments/datasets.tex
> +The value of that is then divided by the minimum of either $N$ of the length of the relevant item set for the user, which in this case is $N$.
```suggestion
The resulting value is then divided by the minimum of either $N$ or the length of the relevant item set for the user, which in this case is equal to $N$.
```

2020-12-14 21:40 UTC, Eduardsen commented on sections/experiments/datasets.tex
> +To find the MAP value, the AP values are simply summed together for each user in $U$ and divideed by $|U|$.
```suggestion
To find the MAP value, the AP values are simply summed together for each user in $U$ and divided by $|U|$.
```

2020-12-14 21:40 UTC, Eduardsen commented on sections/experiments/datasets.tex
> +In the example, the gain $g_ui$ is set to be $1$ when a relevant item is being recommended, and $log_2$ is used.
```suggestion
In the example, the gain $g_{ui}$ is set to be $1$ when a relevant item is being recommended, and $log_2$ is used.
```

2020-12-14 21:40 UTC, Eduardsen commented on sections/experiments/datasets.tex
> +Again, there is only a single user which makes the calculation quite simple
```suggestion
Again, there is only a single user which makes the calculation quite simple.
```

2020-12-14 21:40 UTC, Eduardsen commented on sections/experiments/datasets.tex
> +Then the DCG* is calculated which is done by sorting the recommendation set so the most relevant items comes first, resulting in the biggest possible DCG value.
```suggestion
Then the DCG* is calculated which is done by sorting the recommendation set such that the most relevant items come first, resulting in the largest possible DCG value.
```

2020-12-15 12:52 UTC, Eduardsen approved these changes

2020-12-15 13:35 UTC, Moesgaarda requested changes

2020-12-15 13:35 UTC, Moesgaarda commented on sections/experiments/datasets.tex
> +These values can then be used to calculate the F1-score.
```suggestion
These values can then be used to calculate the F1-score according to \autoref{eqn:f1}.
```

2020-12-16 08:56 UTC, Moesgaarda approved these changes

2020-12-16 09:06 UTC, merged