Synthetic data section
thesis20/report pull request #4
Opened 2020-11-13 11:57 UTC by andpaacoke

2020-11-13 13:01 UTC, Eduardsen commented on sections/Investigation/synthetic-data.tex
> +To enable testing of context-aware recommender system, datasets where the ratings are context-dependent are needed.
```suggestion
To enable testing of context-aware recommender systems, datasets where the ratings are context-dependent are needed.
```

2020-11-13 13:01 UTC, Eduardsen commented on sections/Investigation/synthetic-data.tex
> +One approach is to make a semi-synthetic dataset by a adding a new contextual feature that the ratings will depend on \cite{baltrunasContextItemSplit}.
```suggestion
One approach is to make a semi-synthetic dataset by adding a new contextual feature that the ratings will depend on \cite{baltrunasContextItemSplit}.
```

2020-11-13 13:01 UTC, Eduardsen commented on sections/Investigation/synthetic-data.tex
> +If \texttt{c} is 1, the corresponding rating, between 1 and 5, is increased by 1 if it is not already 5.
```suggestion
If \texttt{c} is 1, the corresponding rating between 1 and 5 is increased by 1, if it is not already 5.
```

2020-11-13 13:01 UTC, Eduardsen commented on sections/Investigation/synthetic-data.tex
> +An $\alpha$ value is then chosen between 0 and 1 which determines the fractions of ratings that are affected by the contextual feature \texttt{c}.
måske eksempel i forklaring 🤔

2020-11-16 10:38 UTC, Moesgaarda requested changes

2020-11-16 10:38 UTC, Moesgaarda commented on sections/Investigation/synthetic-data.tex
> +The idea is to add a new contextual feature \texttt{c} that represents a contextual condition that could affect the rating.
```suggestion
For this approach, the idea is to add a new contextual feature \texttt{c} that represents a contextual condition that could affect the rating.
```

2020-11-16 10:38 UTC, Moesgaarda commented on sections/Investigation/synthetic-data.tex
> +By using this method, one can modify a dataset into being artificially context dependent for testing purposes.
```suggestion
By using this method, one can modify a dataset into being artificially context-dependent for testing purposes.
```

2020-11-16 10:38 UTC, Moesgaarda commented on sections/Investigation/synthetic-data.tex
> +To enable testing of context-aware recommender systems, datasets where the ratings are context-dependent are needed.
```suggestion
To enable testing of context-aware recommender systems, datasets, where the ratings are context-dependent, are needed.
```

2020-11-16 10:38 UTC, Moesgaarda commented on sections/Investigation/synthetic-data.tex
> +An $\alpha$ value is then chosen between 0 and 1 which determines the fractions of ratings that are affected by the contextual feature \texttt{c}.
ja tak 1 stk

2020-11-16 11:49 UTC, andpaacoke commented on sections/Investigation/synthetic-data.tex
> +An $\alpha$ value is then chosen between 0 and 1 which determines the fractions of ratings that are affected by the contextual feature \texttt{c}.
SÅ er der simpelthen et eksempel med

2020-11-16 13:12 UTC, Eduardsen commented on sections/Investigation/synthetic-data.tex
> +To enable testing of context-aware recommender systems, datasets, where the ratings are context-dependent, are needed.
```suggestion
 Datasets where the ratings are context-dependent are needed in order to enable testing of context-aware recommender systems.
```

2020-11-16 14:27 UTC, Moesgaarda approved these changes

2020-11-16 14:31 UTC, Eduardsen approved these changes

2020-11-16 15:14 UTC, merged