Scuffed DeepWalk beskrivelse - Synes den er svær at gå i detaljer med
thesis20/report pull request #49
Opened 2020-12-16 13:34 UTC by andpaacoke

2020-12-16 13:50 UTC, Eduardsen commented on sections/graphrecs/deepwalk.tex
> +This is done using the language model SkipGram, and the result of this is a vector representation of each vertex in d-dimensional space.
```suggestion
This is done using the language model SkipGram, and the result of this is a vector representation of each vertex in $d$-dimensional space.
```

2020-12-16 13:50 UTC, Eduardsen commented on sections/graphrecs/deepwalk.tex
> +Here we opted to go for a k-nearest neighbor (kNN) approach where we find the 10 nearest neighbor user-vertices to a user vertex $u$ using the vector representations.
```suggestion
Here we opted to go for a k-nearest neighbor (kNN) approach where we find the 10 nearest user-vertices to a user vertex $u$ using the vector representations.
```

2020-12-16 13:50 UTC, Eduardsen commented on sections/graphrecs/deepwalk.tex
> +To then generate a rating prediction for a specific item $i$, we look at whether the 10 neighbors have rated item $i$ and use the average of their ratings of $i$ as the predicted rating for user $u$
```suggestion
To then generate a rating prediction for a specific item $i$, we look at whether the 10 neighbors have rated item $i$ and use the average of their ratings of $i$ as the predicted rating for user $u$ on item $i$.
```

2020-12-16 13:50 UTC, Eduardsen commented on sections/graphrecs/deepwalk.tex
> +Deepwalk is an algorithm that uses a deep learning technique to learn social representations of a graph's vertices\cite{DeepWalk}.
```suggestion
DeepWalk is an algorithm that uses a deep learning technique to learn social representations of a graph's vertices\cite{DeepWalk}.
```

2020-12-16 13:57 UTC, Eduardsen commented on sections/graphrecs/deepwalk.tex
> +It makes use of neural language models where the language consists of "sentences" generated by doing random walks between the vertices of the graph.
er det neural eller natural????

2020-12-16 14:07 UTC, Moesgaarda requested changes

2020-12-16 14:07 UTC, Moesgaarda commented on sections/graphrecs/deepwalk.tex
> +It makes use of neural language models where the language consists of "sentences" generated by doing random walks between the vertices of the graph.
```suggestion
It makes use of neural language models where the language consists of "sentences" generated by doing random walks between the nodes of the graph.
```

2020-12-16 14:07 UTC, Moesgaarda commented on sections/graphrecs/deepwalk.tex
> +Deepwalk is an algorithm that uses a deep learning technique to learn social representations of a graph's vertices\cite{DeepWalk}.
```suggestion
DeepWalk is an algorithm that uses a deep learning technique to learn social representations of a graph's nodes\cite{DeepWalk}.
```

2020-12-16 14:07 UTC, Moesgaarda commented on sections/graphrecs/deepwalk.tex
> +By doing this, latent features that capture the neighborhood similarity of the vertices can be learned.
```suggestion
By doing this, latent features that capture the neighborhood similarity of the nodes can be learned.
```

2020-12-16 14:07 UTC, Moesgaarda commented on sections/graphrecs/deepwalk.tex
> +This results in a low dimensional vector representation of each vertex in the graph.
```suggestion
This results in a low dimensional vector representation of each node in the graph.
```

2020-12-16 14:07 UTC, Moesgaarda commented on sections/graphrecs/deepwalk.tex
> +The random walks are done a number of times for each vertex $v_i$.
```suggestion
The random walks are done a number of times for each node $v_i$.
```

2020-12-16 14:07 UTC, Moesgaarda commented on sections/graphrecs/deepwalk.tex
> +The vertices in the walk are chosen at random to form the random walks $W_{vi}$ which are used as "sentences" in the neural language model and the vertices are the "words" of the sentences.
```suggestion
The nodes in the walk are chosen at random to form the random walks $W_{vi}$ which are used as "sentences" in the neural language model and the vertices are the "words" of the sentences.
```

2020-12-16 14:07 UTC, Moesgaarda commented on sections/graphrecs/deepwalk.tex
> +The language model is then used to estimate the likelihood that vertices appear in the same random walk.
```suggestion
The language model is then used to estimate the likelihood that nodes appear in the same random walk.
```

2020-12-16 14:07 UTC, Moesgaarda commented on sections/graphrecs/deepwalk.tex
> +This is done using the language model SkipGram, and the result of this is a vector representation of each vertex in $d$-dimensional space.
```suggestion
This is done using the language model SkipGram, and the result of this is a vector representation of each node in $d$-dimensional space.
```

2020-12-16 14:07 UTC, Moesgaarda commented on sections/graphrecs/deepwalk.tex
> +Here we opted to go for a k-nearest neighbor (kNN) approach where we find the 10 nearest user-vertices to a user vertex $u$ using the vector representations.
```suggestion
Here we opted to go for a k-nearest neighbor (kNN) approach where we find the 10 nearest user nodes to a user node $u$ using the vector representations.
```

2020-12-16 14:12 UTC, andpaacoke commented on sections/graphrecs/deepwalk.tex
> +It makes use of neural language models where the language consists of "sentences" generated by doing random walks between the vertices of the graph.
det er neural!!!!!

2020-12-17 08:23 UTC, Moesgaarda requested changes

2020-12-17 08:23 UTC, Moesgaarda commented on sections/graphrecs/deepwalk.tex
> +The nodes in the walk are chosen at random to form the random walks $W_{vi}$ which are used as "sentences" in the neural language model and the vertices are the "words" of the sentences.
```suggestion
The nodes in the walk are chosen at random to form the random walks $W_{vi}$ which are used as "sentences" in the neural language model and the nodes are the "words" of the sentences.
```

2020-12-17 08:42 UTC, Moesgaarda approved these changes

2020-12-17 08:45 UTC, Eduardsen approved these changes

2020-12-17 08:45 UTC, merged