nemt xd
thesis20/report pull request #66
Opened 2020-12-21 10:45 UTC by Eduardsen

påpeger lige at lightgcn er tiiltænkt collaobrative filtering

2020-12-21 11:19 UTC, andpaacoke approved these changes

2020-12-21 11:51 UTC, Moesgaarda commented on sections/experiments/methods/kgat.tex
> +For the experiments we use the official implementation of the paper.
måske en href med "available on their github"?

2020-12-21 11:51 UTC, Moesgaarda commented on sections/experiments/methods/lightgcn.tex
> +For the experiments we use the official implementation of the paper.
```suggestion
For the experiments, we use the official TensorFlow based implementation of the paper.
```

2020-12-21 11:51 UTC, Moesgaarda commented on sections/experiments/methods/lightgcn.tex
> +For the experiments we use the official implementation of the paper.
der er nemlig både en tensorflow og pytorch

2020-12-21 11:51 UTC, Moesgaarda requested changes
lige et par ting

2020-12-22 09:34 UTC, Moesgaarda approved these changes

2020-12-22 09:53 UTC, merged