recap af experiments i dunno
thesis20/report pull request #70
Opened 2020-12-21 11:57 UTC by andpaacoke

2020-12-21 11:57 UTC, andpaacoke commented
![image](https://user-images.githubusercontent.com/22811754/102774891-24fd6200-438c-11eb-9522-719e3e624f8d.png)

2020-12-21 13:34 UTC, Moesgaarda requested changes

2020-12-21 13:34 UTC, Moesgaarda commented on sections/experiments/results.tex
> +In the experiments we ran a number of methods on four different datasets that contain either contextual information or side-information.
```suggestion
In the experiments, we ran a number of methods on four different datasets that contain either contextual information or side-information.
```

2020-12-21 13:34 UTC, Moesgaarda commented on sections/experiments/results.tex
> +The methods include two context-aware methods, some state-of-the-art graph-based methods and some simple baselines.
```suggestion
The methods included two context-aware methods, some state-of-the-art graph-based methods, and some simple baselines.
```

2020-12-21 13:34 UTC, Moesgaarda commented on sections/experiments/results.tex
> +These methods are evaluated on a number of different metrics that show the performance of the methods on the different datasets.
```suggestion
These methods were evaluated on a number of different metrics that showed their performance on the different datasets.
```

2020-12-22 09:20 UTC, Eduardsen approved these changes

2020-12-22 09:35 UTC, Moesgaarda approved these changes

2020-12-22 09:39 UTC, merged