Obtaining data
thesis20/report pull request #8
Opened 2020-11-17 10:56 UTC by Eduardsen

2020-11-17 11:29 UTC, andpaacoke requested changes

2020-11-17 11:29 UTC, andpaacoke commented on sections/Investigation/utilizing-context.tex
> +Obtaining the data is explicitly is done by approaching relevant people and asking direct questions, or, for example, eliciting the information through a questionnaire.
```suggestion
Obtaining the data is explicitly done by approaching relevant people and asking direct questions, or, for example, eliciting the information through a questionnaire.
```

2020-11-18 10:45 UTC, andpaacoke approved these changes

2020-11-18 10:48 UTC, Moesgaarda requested changes

2020-11-18 10:48 UTC, Moesgaarda commented on sections/Investigation/utilizing-context.tex
> +This contextual information can be obtained through several ways, including: \textit{Explicitly}, \textit{Implicitly} and \textit{inferring} \cite{RecommenderHandbook2015}.
```suggestion
This contextual information can be obtained through several ways, including: \textit{Explicitly}, \textit{Implicitly} and \textit{Inferring} \cite{RecommenderHandbook2015}.
```

2020-11-18 10:48 UTC, Moesgaarda commented on sections/Investigation/utilizing-context.tex
> +This contextual information can be obtained through several ways, including: \textit{Explicitly}, \textit{Implicitly} and \textit{inferring} \cite{RecommenderHandbook2015}.
```suggestion
This contextual information can be obtained through several ways, including: \textit{Explicitly}, \textit{implicitly} and \textit{inferring} \cite{RecommenderHandbook2015}.
```

2020-11-18 10:49 UTC, Moesgaarda approved these changes

2020-11-18 10:49 UTC, merged